### ISSUE TITLE
[Bug]: Firebase in Child Added Listener

### ISSUE THREAD

**Issue by RabahZeineddine** [GogoVega/node-red-contrib-firebase-realtime-database#34]
### What happened?

When using Firebase In node with Child Added Listener and making a node-red deploy, it also triggers on old data. 

So for example, 

```
└── Firebase RTDB/
    └── devices/
        ├── one/
        │   └── ...
        ├── two/
        │   └── ...
        └── ...
```

and the firebase in node listens on devices/  with a child added listener, 

It will trigger on every nested key of the device's JSON. 

### How to reproduce?

1. Add Firebase In node to the flow.
2. Change listener to Child Added.
3. Add a debugger to its output. 
4. add a new record to the path to which the Firebase In node is listening.
5. check the debugger output. 

### Additional comments?

Should be able to select whether to bring old data as a new child or not to trigger the flow.

**Comment by GogoVega** [comment]
Hi Rabah,

The `Child Added` listener is a bit special because **it's triggered once for each existing child** and then again every time a new child is added to the specified path.

You can read more [here](https://firebase.google.com/docs/database/admin/retrieve-data#child-added). 

I am adding a wiki but it will take time...

Kind regards,

Gauthier

**Comment by RabahZeineddine** [comment]
> Hi Rabah,
> 
> The `Child Added` listener is a bit special because **it's triggered once for each existing child** and then again every time a new child is added to the specified path.
> 
> You can read more [here](https://firebase.google.com/docs/database/admin/retrieve-data#child-added).
> 
> I am adding a wiki but it will take time...
> 
> Kind regards,
> 
> Gauthier

Hi @GogoVega ,

I thought that it would be possible to have the option to control this behavior using Node-red events (deploy) if it is possible.

Thank you!

**Comment by GogoVega** [comment]
@RabahZeineddine, could you tell me what you think of the [Firebase IN node documentation](https://github.com/GogoVega/node-red-contrib-firebase-realtime-database/wiki/Firebase-IN). Thank you
