### ISSUE TITLE
@gogovega/node-red-contrib-firebase-realtime-database crashing

### ISSUE THREAD

**Issue by John93-Blynk** [GogoVega/node-red-contrib-firebase-realtime-database#64]
hello,
I'm facing an issue that hopefully someone can help me with. when I configuer @gogovega/node-red-contrib-firebase-realtime-database Node Red keeps crashing and does not start at all unless I remove the pallet. it says something like  "[error] TypeError: app._isFirebaseServerApp is not a function". Am I missing something? can you please tell me what should I do?
I've tried other pallets, and all of them worked as expected.

greetings.

**Comment by GogoVega** [comment]
Hi, can you try restarting Node-RED after installing this palette.

If there is an error in the log, could you copy it in the conversation.

It is not recommended to use several other Firebase palettes because they use the same base package but with different versions.

**Comment by John93-Blynk** [comment]
Thank you for your reply. Much appreciated.

I've attempted to restart Node Red, but with no success. I'm also using one pallet at a time, not multiple simultaneously.
I'm not home at the moment, I will send you the log when I get back home.


Greetings.

**Comment by John93-Blynk** [comment]
Sorry about the delay, I was a little bit busy. Here's the output :

2 Apr 20:52:51 - [info] [database-config:My Database] Connecting to Firebase database: https://test-95211-default-rtdb.firebaseio.com/
2 Apr 20:52:51 - [error] [database-config:My Database] app._isFirebaseServerApp is not a function
2 Apr 20:52:51 - [info] Started flows
2 Apr 20:52:51 - [red] Uncaught Exception:
2 Apr 20:52:51 - [error] TypeError: app._isFirebaseServerApp is not a function
    at AuthImpl.<anonymous> (C:\Users\Valverde WitH US\.node-red\node_modules\@firebase\auth\dist\node\totp-ed04dddc.js:3092:33)
    at step (C:\Users\Valverde WitH US\.node-red\node_modules\tslib\tslib.js:195:27)
    at Object.next (C:\Users\Valverde WitH US\.node-red\node_modules\tslib\tslib.js:176:57)
    at C:\Users\Valverde WitH US\.node-red\node_modules\tslib\tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\Valverde WitH US\.node-red\node_modules\tslib\tslib.js:165:16)
    at AuthImpl.initializeCurrentUser (C:\Users\Valverde WitH US\.node-red\node_modules\@firebase\auth\dist\node\totp-ed04dddc.js:3086:22)
    at AuthImpl.<anonymous> (C:\Users\Valverde WitH US\.node-red\node_modules\@firebase\auth\dist\node\totp-ed04dddc.js:2998:55)
    at step (C:\Users\Valverde WitH US\.node-red\node_modules\tslib\tslib.js:195:27)
    at Object.next (C:\Users\Valverde WitH US\.node-red\node_modules\tslib\tslib.js:176:57)
    at fulfilled (C:\Users\Valverde WitH US\.node-red\node_modules\tslib\tslib.js:166:62)

Note : I've tried it on my Raspberry Pi, and it shows the same error.

greetings.

**Comment by John93-Blynk** [comment]
I've noticed that the topic has been marked as completed without telling me anything about the cause of the error. May I know why?

**Comment by GogoVega** [comment]
Thanks for the hint,
I just released a new version that fixes this problem. Firebase changed an internal function and versioning is surely the cause.
I hope I resolved this issue to prevent this from happening again.

(Sorry, I was writing 😅)

**Comment by John93-Blynk** [comment]
That's great. How am I gonna install the latest release (0.5.5)?

**Comment by GogoVega** [comment]
The Flows library has just been updated, so you can now update from the NR editor (from the Manage Palette) then restart NR. Yep 0.5.5.

**Comment by John93-Blynk** [comment]
Got it. I'll try it and let you know if it works or not.

Thank you so much for your time. Much appreciated.

**Comment by John93-Blynk** [comment]
I've tried it and I have a good news and a bad news.
The good news is Node Red doesn't crash any more, which is a good starting point.
The bad news is it's not working properly. When I configure the database node, it says connected, but the debug window says, "Please check your email address or select 'create a new user' ". Also, if I set the path to msg.topic, it says, "Error: PATH must be a string."  If I set it to a string, it says, "Error: msg.method doesn't exist!"

Can you please try it and see if it's working properly or not? Perhaps I'm doing something wrong or missing something.

Greetings.

**Comment by GogoVega** [comment]
Hi, I played with it a bit and I don't think there's anything wrong. To help you to use this palette you can read this [Wiki](https://github.com/GogoVega/node-red-contrib-firebase-realtime-database/wiki).

I hope this will resolve your situation.

Greetings 🙂

**Comment by John93-Blynk** [comment]
Hello,
I'm at work at the moment. I don't have access to my PC to check. I'll check as soon as I get back home and keep you updated. 
Thank you so much for your time, support, and patience.

Have a great day 😊.

**Comment by GogoVega** [comment]
No worries, I'm at school at the moment.
Thanks and the same 🙂

**Comment by John93-Blynk** [comment]
Hello,
I've followed everything mentioned on the wiki page with no success. Anonymous, Email, and Custom Tokens Generated With Private Key methods are not working at all. The JSON Private Key method seems to be working as expected.
Can you check the email method to see if it's working or not please?
I'm confused because the email method works fine on other palettes.
I know I caused you a headache with my endless questions. Sorry about that, but it's too important. I'm working on a very important project, and I need your palette to complete it. 

Best regards.

**Comment by GogoVega** [comment]
I can confirm that it works for me (all auth methods). Could you send logs/screenshot/step-by-step to understand where your problem is.

**Comment by John93-Blynk** [comment]
Hello,
I've managed to complete my project using the JSON Private Key method, so we can end the discussion here. If you would like me to send you the logs, screenshots, and steps I followed, I'll certainly do that.

Best regards.

**Comment by GogoVega** [comment]
Hi, It would be nice if you send me the step by step of how you did it so I can help you. Thanks !Le 4 avr. 2024 à 09:35, Johnny ***@***.***> a écrit :﻿
Hello,
I've managed to complete my project using the JSON Private Key method, so we can end the discussion here. If you would like me to send you the logs, screenshots, and steps I followed, I'll certainly do that.
Best regards.

**Comment by John93-Blynk** [comment]
Hello,
I will as soon as I get back home.
I would like to thank you so much. You're wasting your time trying to solve my problem. Your help is greatly appreciated.

Best regards 🙂.

**Comment by John93-Blynk** [comment]
Hello,
sorry about the delay. It was a very long, boring day.
 I've tried it one more time, and the debug window still says, "Please check your email address or select 'create a new user' ". That's all.
The steps I followed are the same mentioned here https://github.com/GogoVega/node-red-contrib-firebase-realtime-database/wiki/Authentication#email-and-password
and here
https://github.com/GogoVega/node-red-contrib-firebase-realtime-database/wiki/Config-Node#email-and-password
Can you give me a step by step guide that I can follow?

Greetings.

**Comment by GogoVega** [comment]
Hi, no worries, have you enabled the "Email/Password" method described [here](https://github.com/GogoVega/node-red-contrib-firebase-realtime-database/wiki/Authentication#enable-an-authentication-method) ?

**Comment by John93-Blynk** [comment]
I did that as well, but it's still not working.

**Comment by GogoVega** [comment]
The next step is to create a user, could you complete the "Email" and "Password" fields and select the "Create User" option. The user you are going to create must be a user that you have not registered from the "Users" in "Authentication" page (Firebase Console) - the goal is to see if the node can create a user or if you have a problem with.

**Comment by John93-Blynk** [comment]
I did that as well. No success 😔.

**Comment by John93-Blynk** [comment]
It doesn't add a new user, even though the " create a new user if this one is not exist " option is checked.

**Comment by GogoVega** [comment]
Mmm can you create a user from the "Users" in "Authentication" page  then complete the node. In the meantime, I'll see if Firebase has changed anything for new accounts.

Is "App Check" disabled ?

**Comment by John93-Blynk** [comment]
I'm not sure if "App Check" is disabled or not. I don't have access to my PC at the moment. I'll check as soon as I get back home and let you know.

**Comment by GogoVega** [comment]
I created a new project this way:

1. Create the Firebase Project
2. Enable authentication by clicking on "Start"
3. Enable the “Email/Password” authentication method
4. Build the RTDB
5. Complete the config-node and select “Create User”

=> The user has been created and I have access to my RTDB.

Are you the owner of the project (do you have the rights to create users)?
Did you change the authentication settings (user actions)?

**Comment by John93-Blynk** [comment]
Yes, I'm the owner. I've tried multiple projects as well and didn't change the settings at all.

**Comment by GogoVega** [comment]
Ok, I found an error, I'm looking with Firebase to find out how to resolve it.

Currently only the "Private Key" method works because it is another module.

I will come back to you as soon as I have more information.

**Comment by GogoVega** [comment]
Hi,
I have some answers: The reason the Email method is not working is because [email address enumeration protection](https://cloud.google.com/identity-platform/docs/admin/email-enumeration-protection) is now enabled. You can disable it in "Users Action" in "Parameters" in "Authentication". Regarding the Anonymous method, you probably forgot to enable the method.

Is it good for you?
